# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :test do
     begin
        test_lane()
     rescue => exception
        on_error(exception)
     end
   end

### Methods
  def test_lane
    clear_derived_data
    scan
    on_success()
  end
  
  def on_success()
    UI.success "Successfully finished! All tests passed."
  end

  def on_error(exception)
    UI.error exception
  end

end
