# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies Viper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "SwiftLint"

  # Pods for Movies Viper

  target 'Movies ViperTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'Movies ViperUITests' do
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
