name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: CocoaPod Install
      run: pod install
      working-directory: ./Movies Viper

    - name: Run tests
      run: fastlane test
      working-directory: ./Movies Viper
